version: '3.4'

volumes:
  geth_data:
  geth_data2:
  beacon_node_data:
  beacon_node_follower_data:
  genesis_data:

services:
  execution-node:
    depends_on:
      - lcli-build-genesis
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
    environment:
      GETH_VERBOSITY: 4
      GENESIS_FILE_PATH: /genesis_data/genesis.json
    volumes:
      - 'geth_data:/db'
      - 'genesis_data:/genesis_data'
      # - type: bind
      #   source: ./geth/geth-genesis.json
      #   target: /genesis.json
      - type: bind
        source: ./shared/jwtsecret
        target: /secret/jwtsecret

  execution-node-2:
    depends_on:
      - execution-node
      - lcli-build-genesis
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    environment:
      PEER: execution-node:30303
      GETH_VERBOSITY: 4
      GENESIS_FILE_PATH: /genesis_data/genesis.json
    ports:
      - '8546:8545'
    volumes:
      - 'geth_data2:/db'
      - 'genesis_data:/genesis_data'
      # - type: bind
      #   source: ./geth/geth-genesis.json
      #   target: /genesis.json
      - type: bind
        source: ./shared/jwtsecret
        target: /secret/jwtsecret

  prysm-beacon-node:
    depends_on:
      - execution-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint:
      ['run_beacon_node.sh', '--min-sync-peers=0', '--bootstrap-node=']
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/prysm-priv-key
        target: /etc/prysm-priv-key

  prysm-beacon-node-follower:
    depends_on:
      - execution-node-2
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
      PROCESS_NAME: beacon-node-follower
      BEACON_NODE_RPC: http://prysm-beacon-node:3500
      VERBOSITY: debug
      P2P_PRIV_KEY: /etc/prysm-priv-key
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '4001:4000'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./prysm/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./prysm/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./prysm/prysm-follower-priv-key
        target: /etc/prysm-priv-key

  prysm-validator-node:
    depends_on:
      - prysm-beacon-node
      - jaeger-tracing
    build:
      context: ./prysm
      dockerfile: Dockerfile.prysm
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --interop-num-validators=4
      --interop-start-index=0
      --force-clear-db
      --chain-config-file=/config/chain-config.yml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml

  lodestar-beacon-node:
    depends_on:
      - execution-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node:8545
      PROCESS_NAME: lodestar-beacon-node
    entrypoint: ['run_beacon_node.sh']
    ports:
      - '3500:3500'
      - '13000:13000'
    volumes:
      - 'beacon_node_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh

  lodestar-beacon-node-follower:
    depends_on:
      - execution-node-2
      - lodestar-beacon-node
    build:
      context: ./lodestar
      dockerfile: Dockerfile.lodestar
    environment:
      EXECUTION_NODE_URL: http://execution-node-2:8545
      BEACON_NODE_RPC: http://lodestar-beacon-node:3500
      PROCESS_NAME: lodestar-beacon-node-follower
      VERBOSITY: debug
    entrypoint: run_beacon_node_peer.sh
    ports:
      - '3501:3500'
      - '13001:13000'
    volumes:
      - 'beacon_node_follower_data:/chaindata'
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/chain-config.yml
      - type: bind
        source: ./lodestar/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lodestar/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh

  # TODO: temporary solution for generating genesis, remove this before merge
  lcli-build-genesis:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    environment:
      TESTNET_DIR: /config
    entrypoint: ["generate-genesis.sh"]
    volumes:
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt
      - type: bind
        source: ./lighthouse/generate-genesis.sh
        target: /usr/local/bin/generate-genesis.sh
      - type: bind
        source: ./geth/geth-genesis.json
        target: /genesis.json
      - "genesis_data:/genesis_data"

  lighthouse-beacon-node:
    depends_on:
      - execution-node
      - lcli-build-genesis
    # build:
    #   context: ./lighthouse
    #   dockerfile: Dockerfile.lighthouse
    image: lighthouse-interop
    pull_policy: never
    environment:
      EXECUTION_NODE_URL: "http://execution-node:8551"
      VERBOSITY: debug
      TESTNET_DIR: /config
      GENERATE_GENESIS: "true"
    entrypoint: ["run_beacon_node.sh"]
    ports:
      - "5052:5052"
      - "9000:9000"
    volumes:
      - "beacon_node_data:/chaindata"
      - "genesis_data:/genesis_data"
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /secret/jwtsecret

  lighthouse-beacon-node-follower:
    image: lighthouse-interop
    pull_policy: never
    depends_on:
      - execution-node-2
      - lighthouse-beacon-node
      - lcli-build-genesis
    environment:
      BEACON_NODE_RPC: http://lighthouse-beacon-node:5052
      EXECUTION_NODE_URL: "http://execution-node-2:8551"
      VERBOSITY: debug
      TESTNET_DIR: /config
      GENERATE_GENESIS: "false"
    entrypoint: ["run_beacon_node_peer.sh"]
    ports:
      - "5053:5052"
      - "9001:9000"
    volumes:
      - "beacon_node_follower_data:/chaindata"
      - "genesis_data:/genesis_data"
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt
      - type: bind
        source: ./lighthouse/run_beacon_node.sh
        target: /usr/local/bin/run_beacon_node.sh
      - type: bind
        source: ./lighthouse/run_beacon_node_peer.sh
        target: /usr/local/bin/run_beacon_node_peer.sh
      - type: bind
        source: ./shared/trusted_setup.txt
        target: /config/trusted_setup.txt
      - type: bind
        source: ./shared/jwtsecret
        target: /secret/jwtsecret

  lighthouse-validator-node:
    image: lighthouse-interop
    pull_policy: never
    depends_on:
      - lighthouse-beacon-node-follower
      - lighthouse-beacon-node
    command: >
      lighthouse 
      	vc 
      	--datadir /chaindata 
      	--testnet-dir /config 
      	--init-slashing-protection 
      	--beacon-nodes http://lighthouse-beacon-node:5052
        --suggested-fee-recipient 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    volumes:
      - "beacon_node_data:/chaindata"
      - type: bind
        source: ./shared/chain-config.yml
        target: /config/config.yaml
      - type: bind
        source: ./lighthouse/deploy_block.txt
        target: /config/deploy_block.txt

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
