CONFIG_NAME: "local"
ALTAIR_FORK_EPOCH: 1
BELLATRIX_FORK_EPOCH: 2
EIP4844_FORK_EPOCH: 3
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 3
TERMINAL_TOTAL_DIFFICULTY: 2

# Highest byte set to 0x01 to avoid collisions with mainnet versioning
GENESIS_FORK_VERSION: 0x00000ffd
ALTAIR_FORK_VERSION: 0x01000ffd
BELLATRIX_FORK_VERSION: 0x02000ffd
EIP4844_FORK_VERSION: 0x03000ffd

DOMAIN_BLOBS_SIDECAR: 0x0a000000
